POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.amazon.in/Prestige-Electric-Kettle-PKOSS-1500watts/dp/B01MQZ7J8K?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=_k_EAIaIQobChMIxZuL5dbD5QIVBXZgCh30OA7qEAQYASABEgJ7YvD_BwE_k_&gclid=EAIaIQobChMIxZuL5dbD5QIVBXZgCh30OA7qEAQYASABEgJ7YvD_BwE"
}